Repository ucsb-cs156-w24/proj-gauchoride-w24-7pm-3, pull requests merged in 2024-03, with the labels that each got.

#25 Make admin role toggle options prettier
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/pages/AdminUsersPage.test.js
Labels: Merge Candidate, 5

#28 Modifying Apply to be a Rider link
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptor.java
  src/test/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptorTests.java
Labels: 10

#36 Driver availability controller Admin methods and tests
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java
Labels: Merge Candidate, 10

#33 DriverAvailability: Add DriverAvailabilityTable and Tests
  frontend/src/main/components/DriverAvailability/DriverAvailabilityForm.js
  frontend/src/main/components/DriverAvailability/DriverAvailabilityTable.js
  frontend/src/main/pages/DriverAvailability/DriverAvailabilityEditPage.js
  frontend/src/main/utils/driverAvailabilityUtils.js
  frontend/src/stories/components/DriverAvailability/DriverAvailabilityTable.stories.js
  frontend/src/tests/components/DriverAvailability/DriverAvailabilityForm.test.js
  frontend/src/tests/components/DriverAvailability/DriverAvailabilityTable.test.js
  frontend/src/tests/pages/DriverAvailability/DriverAvailabilityEditPage.test.js
  frontend/src/tests/utils/driverAvailabilityUtils.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java
Labels: Merge Candidate, 20

#53 Admin Rider Application: Review Page
  frontend/src/App.js
  frontend/src/fixtures/riderApplicationFixtures.js
  frontend/src/main/components/RiderApplication/RiderApplicationReviewForm.js
  frontend/src/main/pages/AdminRiderApplication/AdminRiderApplicationReviewPage.js
  frontend/src/stories/components/RiderApplication/RiderApplicationReviewForm.stories.js
  frontend/src/stories/pages/AdminRiderApplication/AdminRiderApplicationReviewPage.stories.js
  frontend/src/tests/components/RiderApplication/RiderApplicationReviewForm.test.js
  frontend/src/tests/pages/AdminRiderApplication/AdminRiderApplicationReviewPage.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationEditPage.test.js
Labels: Merge Candidate, 10

#60 Driver Availability: Add controller DELETE endpoint for driver availability
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java
Labels: Merge Candidate, 5

#49 Added Driver Availability Edit Page and Tests
  frontend/src/stories/pages/DriverAvailability/DriverAvailabilityEditPage.stories.js
  frontend/src/tests/pages/DriverAvailability/DriverAvailabilityEditPage.test.js
Labels: Merge Candidate, 5

#58 Profile Page Badge Spacing
  frontend/src/main/components/Profile/RoleBadge.js
  frontend/src/main/pages/ProfilePage.js
  frontend/src/tests/components/Profile/RoleBadge.test.js
Labels: Merge Candidate, 5

#59 Admin Rider Application Dropdown on NavBar
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/RiderApplication/RiderApplicationIndexPageAdmin.js
  frontend/src/stories/pages/RiderApplication/RiderApplicationIndexPageAdmin.stories.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationIndexPageAdmin.test.js
Labels: 5

#38 DriverAvailability: driverAvailability index page
  frontend/src/main/pages/DriverAvailability/DriverAvailabilityIndexPage.js
  frontend/src/stories/pages/DriverAvailability/DriverAvailabilityIndexPage.stories.js
  frontend/src/tests/components/DriverAvailability/DriverAvailabilityTable.test.js
  frontend/src/tests/pages/DriverAvailability/DriverAvailabilityIndexPage.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
Labels: 10

#51 DriverAvailabilityCreate Page and Stories
  frontend/src/main/components/DriverAvailability/DriverAvailabilityForm.js
  frontend/src/main/pages/DriverAvailability/DriverAvailabilityCreatePage.js
  frontend/src/stories/pages/DriverAvailability/DriverAvailabilityCreate.stories.js
  frontend/src/tests/pages/DriverAvailability/DriverAvailabilityCreatePage.test.js
Labels: 10

#54 Driver Availability: Added Navbar
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/DriverAvailability/DriverAvailabilityEditPage.js
  frontend/src/main/pages/DriverAvailability/DriverAvailabilityIndexPage.js
  frontend/src/tests/pages/DriverAvailability/DriverAvailabilityCreatePage.test.js
  frontend/src/tests/pages/DriverAvailability/DriverAvailabilityEditPage.test.js
  frontend/src/tests/pages/DriverAvailability/DriverAvailabilityIndexPage.test.js
Labels: 5

#61 Bug and Mutation Fixing
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/DriverAvailability/DriverAvailabilityCreatePage.js
  frontend/src/stories/pages/DriverAvailability/DriverAvailabilityCreate.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/DriverAvailability/DriverAvailabilityCreatePage.test.js
Labels: Merge Candidate
